// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
)

const adminAdjustUserBalance = `-- name: AdminAdjustUserBalance :one
UPDATE users
SET balance = balance + ?
WHERE id = ?
RETURNING balance
`

type AdminAdjustUserBalanceParams struct {
	Balance int64 `json:"balance"`
	ID      int64 `json:"id"`
}

func (q *Queries) AdminAdjustUserBalance(ctx context.Context, arg AdminAdjustUserBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminAdjustUserBalance, arg.Balance, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const logAdminAdjustment = `-- name: LogAdminAdjustment :exec
INSERT INTO admin_balance_adjustments (admin_id, user_id, amount, reason)
VALUES (?, ?, ?, ?)
`

type LogAdminAdjustmentParams struct {
	AdminID int64  `json:"admin_id"`
	UserID  int64  `json:"user_id"`
	Amount  int64  `json:"amount"`
	Reason  string `json:"reason"`
}

func (q *Queries) LogAdminAdjustment(ctx context.Context, arg LogAdminAdjustmentParams) error {
	_, err := q.db.ExecContext(ctx, logAdminAdjustment,
		arg.AdminID,
		arg.UserID,
		arg.Amount,
		arg.Reason,
	)
	return err
}
