// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: autofilter.sql

package db

import (
	"context"
)

const getEnabledAutofilterRules = `-- name: GetEnabledAutofilterRules :many
SELECT rule_type, value FROM autofilter_rules WHERE enabled = 1
`

type GetEnabledAutofilterRulesRow struct {
	RuleType string `json:"rule_type"`
	Value    string `json:"value"`
}

func (q *Queries) GetEnabledAutofilterRules(ctx context.Context) ([]GetEnabledAutofilterRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledAutofilterRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnabledAutofilterRulesRow{}
	for rows.Next() {
		var i GetEnabledAutofilterRulesRow
		if err := rows.Scan(&i.RuleType, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
