// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_tokens.sql

package db

import (
	"context"
	"time"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, token_prefix, can_read, can_trade, can_create_markets)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, token_prefix, can_read, can_trade, can_create_markets, created_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID           int64  `json:"user_id"`
	Name             string `json:"name"`
	TokenHash        string `json:"token_hash"`
	TokenPrefix      string `json:"token_prefix"`
	CanRead          int64  `json:"can_read"`
	CanTrade         int64  `json:"can_trade"`
	CanCreateMarkets int64  `json:"can_create_markets"`
}

type CreateAPITokenRow struct {
	ID               int64      `json:"id"`
	UserID           int64      `json:"user_id"`
	Name             string     `json:"name"`
	TokenPrefix      string     `json:"token_prefix"`
	CanRead          int64      `json:"can_read"`
	CanTrade         int64      `json:"can_trade"`
	CanCreateMarkets int64      `json:"can_create_markets"`
	CreatedAt        time.Time  `json:"created_at"`
	LastUsedAt       *time.Time `json:"last_used_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.CanRead,
		arg.CanTrade,
		arg.CanCreateMarkets,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.CanRead,
		&i.CanTrade,
		&i.CanCreateMarkets,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_prefix, token_hash, can_read, can_trade, can_create_markets, created_at, last_used_at, revoked_at
FROM api_tokens
WHERE token_hash = ?
  AND revoked_at IS NULL
LIMIT 1
`

type GetAPITokenByHashRow struct {
	ID               int64      `json:"id"`
	UserID           int64      `json:"user_id"`
	Name             string     `json:"name"`
	TokenPrefix      string     `json:"token_prefix"`
	TokenHash        string     `json:"token_hash"`
	CanRead          int64      `json:"can_read"`
	CanTrade         int64      `json:"can_trade"`
	CanCreateMarkets int64      `json:"can_create_markets"`
	CreatedAt        time.Time  `json:"created_at"`
	LastUsedAt       *time.Time `json:"last_used_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.CanRead,
		&i.CanTrade,
		&i.CanCreateMarkets,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, user_id, name, token_prefix, can_read, can_trade, can_create_markets, created_at, last_used_at, revoked_at
FROM api_tokens
WHERE user_id = ?
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListUserAPITokensRow struct {
	ID               int64      `json:"id"`
	UserID           int64      `json:"user_id"`
	Name             string     `json:"name"`
	TokenPrefix      string     `json:"token_prefix"`
	CanRead          int64      `json:"can_read"`
	CanTrade         int64      `json:"can_trade"`
	CanCreateMarkets int64      `json:"can_create_markets"`
	CreatedAt        time.Time  `json:"created_at"`
	LastUsedAt       *time.Time `json:"last_used_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
}

func (q *Queries) ListUserAPITokens(ctx context.Context, userID int64) ([]ListUserAPITokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAPITokensRow{}
	for rows.Next() {
		var i ListUserAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenPrefix,
			&i.CanRead,
			&i.CanTrade,
			&i.CanCreateMarkets,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserAPIToken = `-- name: RevokeUserAPIToken :one
UPDATE api_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND user_id = ?
  AND revoked_at IS NULL
RETURNING id
`

type RevokeUserAPITokenParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokeUserAPIToken(ctx context.Context, arg RevokeUserAPITokenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, revokeUserAPIToken, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchAPITokenLastUsed, id)
	return err
}
