// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"time"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (market_id, user_id, content, hidden, toxicity_score, moderation_flags)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, market_id, user_id, content, hidden, toxicity_score, moderation_flags, created_at
`

type CreateCommentParams struct {
	MarketID        int64    `json:"market_id"`
	UserID          int64    `json:"user_id"`
	Content         string   `json:"content"`
	Hidden          int64    `json:"hidden"`
	ToxicityScore   *float64 `json:"toxicity_score"`
	ModerationFlags *string  `json:"moderation_flags"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.MarketID,
		arg.UserID,
		arg.Content,
		arg.Hidden,
		arg.ToxicityScore,
		arg.ModerationFlags,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.UserID,
		&i.Content,
		&i.Hidden,
		&i.ToxicityScore,
		&i.ModerationFlags,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, market_id, user_id, content, hidden, toxicity_score, moderation_flags, created_at FROM comments WHERE id = ?
`

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.UserID,
		&i.Content,
		&i.Hidden,
		&i.ToxicityScore,
		&i.ModerationFlags,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentsByMarket = `-- name: GetCommentsByMarket :many
SELECT
    c.id,
    c.market_id,
    c.user_id,
    c.content,
    c.hidden,
    c.toxicity_score,
    c.moderation_flags,
    c.created_at,
    u.display_name AS author_name
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.market_id = ?
  AND (c.hidden = 0 OR c.user_id = ?)
ORDER BY c.created_at ASC
LIMIT 100
`

type GetCommentsByMarketParams struct {
	MarketID int64 `json:"market_id"`
	UserID   int64 `json:"user_id"`
}

type GetCommentsByMarketRow struct {
	ID              int64     `json:"id"`
	MarketID        int64     `json:"market_id"`
	UserID          int64     `json:"user_id"`
	Content         string    `json:"content"`
	Hidden          int64     `json:"hidden"`
	ToxicityScore   *float64  `json:"toxicity_score"`
	ModerationFlags *string   `json:"moderation_flags"`
	CreatedAt       time.Time `json:"created_at"`
	AuthorName      string    `json:"author_name"`
}

// Returns all visible comments plus any hidden comments belonging to the viewer.
// Pass viewer_id=0 for anonymous requests (hidden comments never shown).
func (q *Queries) GetCommentsByMarket(ctx context.Context, arg GetCommentsByMarketParams) ([]GetCommentsByMarketRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByMarket, arg.MarketID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentsByMarketRow{}
	for rows.Next() {
		var i GetCommentsByMarketRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.UserID,
			&i.Content,
			&i.Hidden,
			&i.ToxicityScore,
			&i.ModerationFlags,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
