// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markets.sql

package db

import (
	"context"
	"time"
)

const countMarkets = `-- name: CountMarkets :one
SELECT COUNT(*) FROM markets
WHERE status = ?
  AND (? = '' OR category = ?)
`

type CountMarketsParams struct {
	Status   string      `json:"status"`
	Column2  interface{} `json:"column_2"`
	Category string      `json:"category"`
}

func (q *Queries) CountMarkets(ctx context.Context, arg CountMarketsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMarkets, arg.Status, arg.Column2, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMarket = `-- name: CreateMarket :one
INSERT INTO markets (title, description, category, resolution_criteria, resolution_deadline, created_by, liquidity_param, resolution_type, resolution_threshold)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, description, category, resolution_criteria, resolution_deadline, status, resolved_outcome_id, created_by, resolved_by, created_at, resolved_at, liquidity_param, resolution_type, resolution_threshold, resolution_evidence
`

type CreateMarketParams struct {
	Title               string    `json:"title"`
	Description         string    `json:"description"`
	Category            string    `json:"category"`
	ResolutionCriteria  string    `json:"resolution_criteria"`
	ResolutionDeadline  time.Time `json:"resolution_deadline"`
	CreatedBy           int64     `json:"created_by"`
	LiquidityParam      float64   `json:"liquidity_param"`
	ResolutionType      string    `json:"resolution_type"`
	ResolutionThreshold *string   `json:"resolution_threshold"`
}

func (q *Queries) CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error) {
	row := q.db.QueryRowContext(ctx, createMarket,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ResolutionCriteria,
		arg.ResolutionDeadline,
		arg.CreatedBy,
		arg.LiquidityParam,
		arg.ResolutionType,
		arg.ResolutionThreshold,
	)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ResolutionCriteria,
		&i.ResolutionDeadline,
		&i.Status,
		&i.ResolvedOutcomeID,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.LiquidityParam,
		&i.ResolutionType,
		&i.ResolutionThreshold,
		&i.ResolutionEvidence,
	)
	return i, err
}

const createOutcome = `-- name: CreateOutcome :one
INSERT INTO market_outcomes (market_id, label, sort_order)
VALUES (?, ?, ?)
RETURNING id, market_id, label, shares, sort_order
`

type CreateOutcomeParams struct {
	MarketID  int64  `json:"market_id"`
	Label     string `json:"label"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateOutcome(ctx context.Context, arg CreateOutcomeParams) (MarketOutcome, error) {
	row := q.db.QueryRowContext(ctx, createOutcome, arg.MarketID, arg.Label, arg.SortOrder)
	var i MarketOutcome
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.Label,
		&i.Shares,
		&i.SortOrder,
	)
	return i, err
}

const getActivePendingMarketTitles = `-- name: GetActivePendingMarketTitles :many
SELECT title FROM markets
WHERE status IN ('pending_review', 'active', 'resolution_requested')
`

// Returns titles of all non-archived markets for duplicate-title detection.
func (q *Queries) GetActivePendingMarketTitles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActivePendingMarketTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketByID = `-- name: GetMarketByID :one
SELECT m.id, m.title, m.description, m.category, m.resolution_criteria, m.resolution_deadline, m.status, m.resolved_outcome_id, m.created_by, m.resolved_by, m.created_at, m.resolved_at, m.liquidity_param, m.resolution_type, m.resolution_threshold, m.resolution_evidence, u.display_name AS creator_name, ru.display_name AS resolver_name
FROM markets m
JOIN users u ON u.id = m.created_by
LEFT JOIN users ru ON ru.id = m.resolved_by
WHERE m.id = ?
LIMIT 1
`

type GetMarketByIDRow struct {
	ID                  int64      `json:"id"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Category            string     `json:"category"`
	ResolutionCriteria  string     `json:"resolution_criteria"`
	ResolutionDeadline  time.Time  `json:"resolution_deadline"`
	Status              string     `json:"status"`
	ResolvedOutcomeID   *int64     `json:"resolved_outcome_id"`
	CreatedBy           int64      `json:"created_by"`
	ResolvedBy          *int64     `json:"resolved_by"`
	CreatedAt           time.Time  `json:"created_at"`
	ResolvedAt          *time.Time `json:"resolved_at"`
	LiquidityParam      float64    `json:"liquidity_param"`
	ResolutionType      string     `json:"resolution_type"`
	ResolutionThreshold *string    `json:"resolution_threshold"`
	ResolutionEvidence  *string    `json:"resolution_evidence"`
	CreatorName         string     `json:"creator_name"`
	ResolverName        *string    `json:"resolver_name"`
}

func (q *Queries) GetMarketByID(ctx context.Context, id int64) (GetMarketByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMarketByID, id)
	var i GetMarketByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ResolutionCriteria,
		&i.ResolutionDeadline,
		&i.Status,
		&i.ResolvedOutcomeID,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.LiquidityParam,
		&i.ResolutionType,
		&i.ResolutionThreshold,
		&i.ResolutionEvidence,
		&i.CreatorName,
		&i.ResolverName,
	)
	return i, err
}

const getMarketPriceHistory = `-- name: GetMarketPriceHistory :many
SELECT t.price_at_trade, o.label AS outcome_label, t.created_at
FROM trades t
JOIN market_outcomes o ON o.id = t.outcome_id
WHERE t.market_id = ?
ORDER BY t.created_at ASC
`

type GetMarketPriceHistoryRow struct {
	PriceAtTrade float64   `json:"price_at_trade"`
	OutcomeLabel string    `json:"outcome_label"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetMarketPriceHistory(ctx context.Context, marketID int64) ([]GetMarketPriceHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getMarketPriceHistory, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMarketPriceHistoryRow{}
	for rows.Next() {
		var i GetMarketPriceHistoryRow
		if err := rows.Scan(&i.PriceAtTrade, &i.OutcomeLabel, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutcomesByMarketID = `-- name: GetOutcomesByMarketID :many
SELECT id, market_id, label, shares, sort_order FROM market_outcomes
WHERE market_id = ?
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) GetOutcomesByMarketID(ctx context.Context, marketID int64) ([]MarketOutcome, error) {
	rows, err := q.db.QueryContext(ctx, getOutcomesByMarketID, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketOutcome{}
	for rows.Next() {
		var i MarketOutcome
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.Label,
			&i.Shares,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeadlinePassedMarkets = `-- name: ListDeadlinePassedMarkets :many
SELECT m.id, m.title, m.description, m.category, m.resolution_criteria, m.resolution_deadline, m.status, m.resolved_outcome_id, m.created_by, m.resolved_by, m.created_at, m.resolved_at, m.liquidity_param, m.resolution_type, m.resolution_threshold, m.resolution_evidence, u.display_name AS creator_name
FROM markets m
JOIN users u ON u.id = m.created_by
WHERE m.status = 'deadline_passed'
ORDER BY m.resolution_deadline ASC, m.created_at ASC
`

type ListDeadlinePassedMarketsRow struct {
	ID                  int64      `json:"id"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Category            string     `json:"category"`
	ResolutionCriteria  string     `json:"resolution_criteria"`
	ResolutionDeadline  time.Time  `json:"resolution_deadline"`
	Status              string     `json:"status"`
	ResolvedOutcomeID   *int64     `json:"resolved_outcome_id"`
	CreatedBy           int64      `json:"created_by"`
	ResolvedBy          *int64     `json:"resolved_by"`
	CreatedAt           time.Time  `json:"created_at"`
	ResolvedAt          *time.Time `json:"resolved_at"`
	LiquidityParam      float64    `json:"liquidity_param"`
	ResolutionType      string     `json:"resolution_type"`
	ResolutionThreshold *string    `json:"resolution_threshold"`
	ResolutionEvidence  *string    `json:"resolution_evidence"`
	CreatorName         string     `json:"creator_name"`
}

func (q *Queries) ListDeadlinePassedMarkets(ctx context.Context) ([]ListDeadlinePassedMarketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeadlinePassedMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeadlinePassedMarketsRow{}
	for rows.Next() {
		var i ListDeadlinePassedMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ResolutionCriteria,
			&i.ResolutionDeadline,
			&i.Status,
			&i.ResolvedOutcomeID,
			&i.CreatedBy,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.LiquidityParam,
			&i.ResolutionType,
			&i.ResolutionThreshold,
			&i.ResolutionEvidence,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkets = `-- name: ListMarkets :many
SELECT m.id, m.title, m.description, m.category, m.resolution_criteria, m.resolution_deadline, m.status, m.resolved_outcome_id, m.created_by, m.resolved_by, m.created_at, m.resolved_at, m.liquidity_param, m.resolution_type, m.resolution_threshold, m.resolution_evidence, u.display_name AS creator_name,
       (SELECT COUNT(*) FROM comments c WHERE c.market_id = m.id AND c.hidden = 0) AS comment_count
FROM markets m
JOIN users u ON u.id = m.created_by
WHERE m.status = ?
  AND (? = '' OR m.category = ?)
ORDER BY m.created_at DESC
LIMIT ? OFFSET ?
`

type ListMarketsParams struct {
	Status   string      `json:"status"`
	Column2  interface{} `json:"column_2"`
	Category string      `json:"category"`
	Limit    int64       `json:"limit"`
	Offset   int64       `json:"offset"`
}

type ListMarketsRow struct {
	ID                  int64      `json:"id"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Category            string     `json:"category"`
	ResolutionCriteria  string     `json:"resolution_criteria"`
	ResolutionDeadline  time.Time  `json:"resolution_deadline"`
	Status              string     `json:"status"`
	ResolvedOutcomeID   *int64     `json:"resolved_outcome_id"`
	CreatedBy           int64      `json:"created_by"`
	ResolvedBy          *int64     `json:"resolved_by"`
	CreatedAt           time.Time  `json:"created_at"`
	ResolvedAt          *time.Time `json:"resolved_at"`
	LiquidityParam      float64    `json:"liquidity_param"`
	ResolutionType      string     `json:"resolution_type"`
	ResolutionThreshold *string    `json:"resolution_threshold"`
	ResolutionEvidence  *string    `json:"resolution_evidence"`
	CreatorName         string     `json:"creator_name"`
	CommentCount        int64      `json:"comment_count"`
}

func (q *Queries) ListMarkets(ctx context.Context, arg ListMarketsParams) ([]ListMarketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarkets,
		arg.Status,
		arg.Column2,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsRow{}
	for rows.Next() {
		var i ListMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ResolutionCriteria,
			&i.ResolutionDeadline,
			&i.Status,
			&i.ResolvedOutcomeID,
			&i.CreatedBy,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.LiquidityParam,
			&i.ResolutionType,
			&i.ResolutionThreshold,
			&i.ResolutionEvidence,
			&i.CreatorName,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMarkets = `-- name: ListPendingMarkets :many
SELECT m.id, m.title, m.description, m.category, m.resolution_criteria, m.resolution_deadline, m.status, m.resolved_outcome_id, m.created_by, m.resolved_by, m.created_at, m.resolved_at, m.liquidity_param, m.resolution_type, m.resolution_threshold, m.resolution_evidence, u.display_name AS creator_name
FROM markets m
JOIN users u ON u.id = m.created_by
WHERE m.status = 'pending_review'
ORDER BY m.created_at ASC
`

type ListPendingMarketsRow struct {
	ID                  int64      `json:"id"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Category            string     `json:"category"`
	ResolutionCriteria  string     `json:"resolution_criteria"`
	ResolutionDeadline  time.Time  `json:"resolution_deadline"`
	Status              string     `json:"status"`
	ResolvedOutcomeID   *int64     `json:"resolved_outcome_id"`
	CreatedBy           int64      `json:"created_by"`
	ResolvedBy          *int64     `json:"resolved_by"`
	CreatedAt           time.Time  `json:"created_at"`
	ResolvedAt          *time.Time `json:"resolved_at"`
	LiquidityParam      float64    `json:"liquidity_param"`
	ResolutionType      string     `json:"resolution_type"`
	ResolutionThreshold *string    `json:"resolution_threshold"`
	ResolutionEvidence  *string    `json:"resolution_evidence"`
	CreatorName         string     `json:"creator_name"`
}

func (q *Queries) ListPendingMarkets(ctx context.Context) ([]ListPendingMarketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingMarketsRow{}
	for rows.Next() {
		var i ListPendingMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ResolutionCriteria,
			&i.ResolutionDeadline,
			&i.Status,
			&i.ResolvedOutcomeID,
			&i.CreatedBy,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.LiquidityParam,
			&i.ResolutionType,
			&i.ResolutionThreshold,
			&i.ResolutionEvidence,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarketStatus = `-- name: UpdateMarketStatus :exec
UPDATE markets SET status = ? WHERE id = ?
`

type UpdateMarketStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateMarketStatus(ctx context.Context, arg UpdateMarketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMarketStatus, arg.Status, arg.ID)
	return err
}

const updateOutcomeShares = `-- name: UpdateOutcomeShares :exec
UPDATE market_outcomes SET shares = ? WHERE id = ?
`

type UpdateOutcomeSharesParams struct {
	Shares float64 `json:"shares"`
	ID     int64   `json:"id"`
}

func (q *Queries) UpdateOutcomeShares(ctx context.Context, arg UpdateOutcomeSharesParams) error {
	_, err := q.db.ExecContext(ctx, updateOutcomeShares, arg.Shares, arg.ID)
	return err
}
