// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markets.sql

package db

import (
	"context"
	"time"
)

const countMarkets = `-- name: CountMarkets :one
SELECT COUNT(*) FROM markets
WHERE status = ?
  AND (? = '' OR category = ?)
`

type CountMarketsParams struct {
	Status   string      `json:"status"`
	Column2  interface{} `json:"column_2"`
	Category string      `json:"category"`
}

func (q *Queries) CountMarkets(ctx context.Context, arg CountMarketsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMarkets, arg.Status, arg.Column2, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMarket = `-- name: CreateMarket :one
INSERT INTO markets (title, description, category, resolution_criteria, resolution_deadline, created_by, liquidity_param)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, description, category, resolution_criteria, resolution_deadline, status, resolution, created_by, resolved_by, created_at, resolved_at, liquidity_param, yes_shares, no_shares
`

type CreateMarketParams struct {
	Title              string    `json:"title"`
	Description        string    `json:"description"`
	Category           string    `json:"category"`
	ResolutionCriteria string    `json:"resolution_criteria"`
	ResolutionDeadline time.Time `json:"resolution_deadline"`
	CreatedBy          int64     `json:"created_by"`
	LiquidityParam     float64   `json:"liquidity_param"`
}

func (q *Queries) CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error) {
	row := q.db.QueryRowContext(ctx, createMarket,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ResolutionCriteria,
		arg.ResolutionDeadline,
		arg.CreatedBy,
		arg.LiquidityParam,
	)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ResolutionCriteria,
		&i.ResolutionDeadline,
		&i.Status,
		&i.Resolution,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.LiquidityParam,
		&i.YesShares,
		&i.NoShares,
	)
	return i, err
}

const getActivePendingMarketTitles = `-- name: GetActivePendingMarketTitles :many
SELECT title FROM markets
WHERE status IN ('pending_review', 'active', 'resolution_requested')
`

// Returns titles of all non-archived markets for duplicate-title detection.
func (q *Queries) GetActivePendingMarketTitles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActivePendingMarketTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarketByID = `-- name: GetMarketByID :one
SELECT m.id, m.title, m.description, m.category, m.resolution_criteria, m.resolution_deadline, m.status, m.resolution, m.created_by, m.resolved_by, m.created_at, m.resolved_at, m.liquidity_param, m.yes_shares, m.no_shares, u.display_name AS creator_name
FROM markets m
JOIN users u ON u.id = m.created_by
WHERE m.id = ?
LIMIT 1
`

type GetMarketByIDRow struct {
	ID                 int64      `json:"id"`
	Title              string     `json:"title"`
	Description        string     `json:"description"`
	Category           string     `json:"category"`
	ResolutionCriteria string     `json:"resolution_criteria"`
	ResolutionDeadline time.Time  `json:"resolution_deadline"`
	Status             string     `json:"status"`
	Resolution         *string    `json:"resolution"`
	CreatedBy          int64      `json:"created_by"`
	ResolvedBy         *int64     `json:"resolved_by"`
	CreatedAt          time.Time  `json:"created_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	LiquidityParam     float64    `json:"liquidity_param"`
	YesShares          float64    `json:"yes_shares"`
	NoShares           float64    `json:"no_shares"`
	CreatorName        string     `json:"creator_name"`
}

func (q *Queries) GetMarketByID(ctx context.Context, id int64) (GetMarketByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMarketByID, id)
	var i GetMarketByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ResolutionCriteria,
		&i.ResolutionDeadline,
		&i.Status,
		&i.Resolution,
		&i.CreatedBy,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.LiquidityParam,
		&i.YesShares,
		&i.NoShares,
		&i.CreatorName,
	)
	return i, err
}

const getMarketPriceHistory = `-- name: GetMarketPriceHistory :many
SELECT price_at_trade, side, created_at
FROM trades
WHERE market_id = ?
ORDER BY created_at ASC
`

type GetMarketPriceHistoryRow struct {
	PriceAtTrade float64   `json:"price_at_trade"`
	Side         string    `json:"side"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetMarketPriceHistory(ctx context.Context, marketID int64) ([]GetMarketPriceHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getMarketPriceHistory, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMarketPriceHistoryRow{}
	for rows.Next() {
		var i GetMarketPriceHistoryRow
		if err := rows.Scan(&i.PriceAtTrade, &i.Side, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkets = `-- name: ListMarkets :many
SELECT m.id, m.title, m.description, m.category, m.resolution_criteria, m.resolution_deadline, m.status, m.resolution, m.created_by, m.resolved_by, m.created_at, m.resolved_at, m.liquidity_param, m.yes_shares, m.no_shares, u.display_name AS creator_name
FROM markets m
JOIN users u ON u.id = m.created_by
WHERE m.status = ?
  AND (? = '' OR m.category = ?)
ORDER BY m.created_at DESC
LIMIT ? OFFSET ?
`

type ListMarketsParams struct {
	Status   string      `json:"status"`
	Column2  interface{} `json:"column_2"`
	Category string      `json:"category"`
	Limit    int64       `json:"limit"`
	Offset   int64       `json:"offset"`
}

type ListMarketsRow struct {
	ID                 int64      `json:"id"`
	Title              string     `json:"title"`
	Description        string     `json:"description"`
	Category           string     `json:"category"`
	ResolutionCriteria string     `json:"resolution_criteria"`
	ResolutionDeadline time.Time  `json:"resolution_deadline"`
	Status             string     `json:"status"`
	Resolution         *string    `json:"resolution"`
	CreatedBy          int64      `json:"created_by"`
	ResolvedBy         *int64     `json:"resolved_by"`
	CreatedAt          time.Time  `json:"created_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	LiquidityParam     float64    `json:"liquidity_param"`
	YesShares          float64    `json:"yes_shares"`
	NoShares           float64    `json:"no_shares"`
	CreatorName        string     `json:"creator_name"`
}

func (q *Queries) ListMarkets(ctx context.Context, arg ListMarketsParams) ([]ListMarketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarkets,
		arg.Status,
		arg.Column2,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsRow{}
	for rows.Next() {
		var i ListMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ResolutionCriteria,
			&i.ResolutionDeadline,
			&i.Status,
			&i.Resolution,
			&i.CreatedBy,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.LiquidityParam,
			&i.YesShares,
			&i.NoShares,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMarkets = `-- name: ListPendingMarkets :many
SELECT m.id, m.title, m.description, m.category, m.resolution_criteria, m.resolution_deadline, m.status, m.resolution, m.created_by, m.resolved_by, m.created_at, m.resolved_at, m.liquidity_param, m.yes_shares, m.no_shares, u.display_name AS creator_name
FROM markets m
JOIN users u ON u.id = m.created_by
WHERE m.status = 'pending_review'
ORDER BY m.created_at ASC
`

type ListPendingMarketsRow struct {
	ID                 int64      `json:"id"`
	Title              string     `json:"title"`
	Description        string     `json:"description"`
	Category           string     `json:"category"`
	ResolutionCriteria string     `json:"resolution_criteria"`
	ResolutionDeadline time.Time  `json:"resolution_deadline"`
	Status             string     `json:"status"`
	Resolution         *string    `json:"resolution"`
	CreatedBy          int64      `json:"created_by"`
	ResolvedBy         *int64     `json:"resolved_by"`
	CreatedAt          time.Time  `json:"created_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	LiquidityParam     float64    `json:"liquidity_param"`
	YesShares          float64    `json:"yes_shares"`
	NoShares           float64    `json:"no_shares"`
	CreatorName        string     `json:"creator_name"`
}

func (q *Queries) ListPendingMarkets(ctx context.Context) ([]ListPendingMarketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingMarketsRow{}
	for rows.Next() {
		var i ListPendingMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ResolutionCriteria,
			&i.ResolutionDeadline,
			&i.Status,
			&i.Resolution,
			&i.CreatedBy,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.LiquidityParam,
			&i.YesShares,
			&i.NoShares,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMarket = `-- name: ResolveMarket :exec
UPDATE markets
SET status      = 'resolved',
    resolution  = ?,
    resolved_by = ?,
    resolved_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type ResolveMarketParams struct {
	Resolution *string `json:"resolution"`
	ResolvedBy *int64  `json:"resolved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) ResolveMarket(ctx context.Context, arg ResolveMarketParams) error {
	_, err := q.db.ExecContext(ctx, resolveMarket, arg.Resolution, arg.ResolvedBy, arg.ID)
	return err
}

const updateMarketAMMState = `-- name: UpdateMarketAMMState :exec
UPDATE markets
SET yes_shares = ?,
    no_shares  = ?
WHERE id = ?
`

type UpdateMarketAMMStateParams struct {
	YesShares float64 `json:"yes_shares"`
	NoShares  float64 `json:"no_shares"`
	ID        int64   `json:"id"`
}

func (q *Queries) UpdateMarketAMMState(ctx context.Context, arg UpdateMarketAMMStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMarketAMMState, arg.YesShares, arg.NoShares, arg.ID)
	return err
}

const updateMarketStatus = `-- name: UpdateMarketStatus :exec
UPDATE markets SET status = ? WHERE id = ?
`

type UpdateMarketStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateMarketStatus(ctx context.Context, arg UpdateMarketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMarketStatus, arg.Status, arg.ID)
	return err
}
