// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AutofilterRule struct {
	ID        int64     `json:"id"`
	RuleType  string    `json:"rule_type"`
	Value     string    `json:"value"`
	Enabled   int64     `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
}

type Market struct {
	ID                 int64      `json:"id"`
	Title              string     `json:"title"`
	Description        string     `json:"description"`
	Category           string     `json:"category"`
	ResolutionCriteria string     `json:"resolution_criteria"`
	ResolutionDeadline time.Time  `json:"resolution_deadline"`
	Status             string     `json:"status"`
	Resolution         *string    `json:"resolution"`
	CreatedBy          int64      `json:"created_by"`
	ResolvedBy         *int64     `json:"resolved_by"`
	CreatedAt          time.Time  `json:"created_at"`
	ResolvedAt         *time.Time `json:"resolved_at"`
	LiquidityParam     float64    `json:"liquidity_param"`
	YesShares          float64    `json:"yes_shares"`
	NoShares           float64    `json:"no_shares"`
}

type ModerationAction struct {
	ID          int64     `json:"id"`
	MarketID    int64     `json:"market_id"`
	ModeratorID int64     `json:"moderator_id"`
	Action      string    `json:"action"`
	Reason      string    `json:"reason"`
	CreatedAt   time.Time `json:"created_at"`
}

type Position struct {
	UserID    int64   `json:"user_id"`
	MarketID  int64   `json:"market_id"`
	YesShares float64 `json:"yes_shares"`
	NoShares  float64 `json:"no_shares"`
}

type Report struct {
	ID         int64     `json:"id"`
	ReporterID int64     `json:"reporter_id"`
	MarketID   int64     `json:"market_id"`
	Reason     string    `json:"reason"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
}

type Trade struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	MarketID     int64     `json:"market_id"`
	Side         string    `json:"side"`
	Action       string    `json:"action"`
	Shares       float64   `json:"shares"`
	Cost         int64     `json:"cost"`
	PriceAtTrade float64   `json:"price_at_trade"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID          int64     `json:"id"`
	ScidSub     string    `json:"scid_sub"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
	Balance     int64     `json:"balance"`
	IsModerator int64     `json:"is_moderator"`
	IsAdmin     int64     `json:"is_admin"`
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`
}
