// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AdminBalanceAdjustment struct {
	ID        int64     `json:"id"`
	AdminID   int64     `json:"admin_id"`
	UserID    int64     `json:"user_id"`
	Amount    int64     `json:"amount"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
}

type AutofilterRule struct {
	ID        int64     `json:"id"`
	RuleType  string    `json:"rule_type"`
	Value     string    `json:"value"`
	Enabled   int64     `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
}

type Comment struct {
	ID              int64     `json:"id"`
	MarketID        int64     `json:"market_id"`
	UserID          int64     `json:"user_id"`
	Content         string    `json:"content"`
	Hidden          int64     `json:"hidden"`
	ToxicityScore   *float64  `json:"toxicity_score"`
	ModerationFlags *string   `json:"moderation_flags"`
	CreatedAt       time.Time `json:"created_at"`
}

type DetectedPatch struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	PatchVersion string    `json:"patch_version"`
	ThreadUrl    string    `json:"thread_url"`
	FirstSeenAt  time.Time `json:"first_seen_at"`
	Notified     int64     `json:"notified"`
}

type Market struct {
	ID                  int64      `json:"id"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Category            string     `json:"category"`
	ResolutionCriteria  string     `json:"resolution_criteria"`
	ResolutionDeadline  time.Time  `json:"resolution_deadline"`
	Status              string     `json:"status"`
	ResolvedOutcomeID   *int64     `json:"resolved_outcome_id"`
	CreatedBy           int64      `json:"created_by"`
	ResolvedBy          *int64     `json:"resolved_by"`
	CreatedAt           time.Time  `json:"created_at"`
	ResolvedAt          *time.Time `json:"resolved_at"`
	LiquidityParam      float64    `json:"liquidity_param"`
	ResolutionType      string     `json:"resolution_type"`
	ResolutionThreshold *string    `json:"resolution_threshold"`
	ResolutionEvidence  *string    `json:"resolution_evidence"`
}

type MarketOutcome struct {
	ID        int64   `json:"id"`
	MarketID  int64   `json:"market_id"`
	Label     string  `json:"label"`
	Shares    float64 `json:"shares"`
	SortOrder int64   `json:"sort_order"`
}

type ModerationAction struct {
	ID          int64     `json:"id"`
	MarketID    int64     `json:"market_id"`
	ModeratorID int64     `json:"moderator_id"`
	Action      string    `json:"action"`
	Reason      string    `json:"reason"`
	CreatedAt   time.Time `json:"created_at"`
}

type Position struct {
	UserID    int64   `json:"user_id"`
	MarketID  int64   `json:"market_id"`
	OutcomeID int64   `json:"outcome_id"`
	Shares    float64 `json:"shares"`
}

type Report struct {
	ID         int64     `json:"id"`
	ReporterID int64     `json:"reporter_id"`
	MarketID   int64     `json:"market_id"`
	Reason     string    `json:"reason"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
}

type ResolutionRequestDetail struct {
	MarketID    int64     `json:"market_id"`
	RequestedBy int64     `json:"requested_by"`
	Link        *string   `json:"link"`
	Note        *string   `json:"note"`
	CreatedAt   time.Time `json:"created_at"`
}

type Trade struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	MarketID     int64     `json:"market_id"`
	OutcomeID    int64     `json:"outcome_id"`
	Action       string    `json:"action"`
	Shares       float64   `json:"shares"`
	Cost         int64     `json:"cost"`
	PriceAtTrade float64   `json:"price_at_trade"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID               int64     `json:"id"`
	ScidSub          string    `json:"scid_sub"`
	DisplayName      string    `json:"display_name"`
	Email            string    `json:"email"`
	Balance          int64     `json:"balance"`
	IsModerator      int64     `json:"is_moderator"`
	IsAdmin          int64     `json:"is_admin"`
	CreatedAt        time.Time `json:"created_at"`
	LastLoginAt      time.Time `json:"last_login_at"`
	RsiHandle        *string   `json:"rsi_handle"`
	RsiVerifiedAt    *string   `json:"rsi_verified_at"`
	RsiEnlisted      *string   `json:"rsi_enlisted"`
	RsiCitizenRecord *string   `json:"rsi_citizen_record"`
	AvatarUrl        *string   `json:"avatar_url"`
	IsRsiVerified    int64     `json:"is_rsi_verified"`
}

type UserBadge struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	BadgeKey  string    `json:"badge_key"`
	AwardedAt time.Time `json:"awarded_at"`
}

type WeeklyPayoutLog struct {
	ID        int64     `json:"id"`
	WeekKey   string    `json:"week_key"`
	UserCount int64     `json:"user_count"`
	PaidAt    time.Time `json:"paid_at"`
}
