// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patches.sql

package db

import (
	"context"
)

const insertPatch = `-- name: InsertPatch :exec
INSERT OR IGNORE INTO detected_patches (title, patch_version, thread_url)
VALUES (?, ?, ?)
`

type InsertPatchParams struct {
	Title        string `json:"title"`
	PatchVersion string `json:"patch_version"`
	ThreadUrl    string `json:"thread_url"`
}

func (q *Queries) InsertPatch(ctx context.Context, arg InsertPatchParams) error {
	_, err := q.db.ExecContext(ctx, insertPatch, arg.Title, arg.PatchVersion, arg.ThreadUrl)
	return err
}

const listAllPatches = `-- name: ListAllPatches :many
SELECT id, title, patch_version, thread_url, first_seen_at, notified FROM detected_patches ORDER BY first_seen_at DESC LIMIT 50
`

func (q *Queries) ListAllPatches(ctx context.Context) ([]DetectedPatch, error) {
	rows, err := q.db.QueryContext(ctx, listAllPatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedPatch{}
	for rows.Next() {
		var i DetectedPatch
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PatchVersion,
			&i.ThreadUrl,
			&i.FirstSeenAt,
			&i.Notified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewPatches = `-- name: ListNewPatches :many
SELECT id, title, patch_version, thread_url, first_seen_at, notified FROM detected_patches WHERE notified = 0 ORDER BY first_seen_at DESC
`

func (q *Queries) ListNewPatches(ctx context.Context) ([]DetectedPatch, error) {
	rows, err := q.db.QueryContext(ctx, listNewPatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedPatch{}
	for rows.Next() {
		var i DetectedPatch
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PatchVersion,
			&i.ThreadUrl,
			&i.FirstSeenAt,
			&i.Notified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPatchNotified = `-- name: MarkPatchNotified :exec
UPDATE detected_patches SET notified = 1 WHERE id = ?
`

func (q *Queries) MarkPatchNotified(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPatchNotified, id)
	return err
}
