// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AdminAdjustUserBalance(ctx context.Context, arg AdminAdjustUserBalanceParams) (int64, error)
	CountMarkets(ctx context.Context, arg CountMarketsParams) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error)
	CreateOutcome(ctx context.Context, arg CreateOutcomeParams) (MarketOutcome, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteComment(ctx context.Context, id int64) error
	// Returns titles of all non-archived markets for duplicate-title detection.
	GetActivePendingMarketTitles(ctx context.Context) ([]string, error)
	GetCommentByID(ctx context.Context, id int64) (Comment, error)
	// Returns all visible comments plus any hidden comments belonging to the viewer.
	// Pass viewer_id=0 for anonymous requests (hidden comments never shown).
	GetCommentsByMarket(ctx context.Context, arg GetCommentsByMarketParams) ([]GetCommentsByMarketRow, error)
	GetEnabledAutofilterRules(ctx context.Context) ([]GetEnabledAutofilterRulesRow, error)
	GetLeaderboard(ctx context.Context, limit int64) ([]GetLeaderboardRow, error)
	GetMarketByID(ctx context.Context, id int64) (GetMarketByIDRow, error)
	GetMarketPriceHistory(ctx context.Context, marketID int64) ([]GetMarketPriceHistoryRow, error)
	// Returns aggregate trade statistics for a single market.
	GetMarketStats(ctx context.Context, marketID int64) (GetMarketStatsRow, error)
	GetMarketTrades(ctx context.Context, arg GetMarketTradesParams) ([]GetMarketTradesRow, error)
	GetOutcomesByMarketID(ctx context.Context, marketID int64) ([]MarketOutcome, error)
	GetPositionsForResolution(ctx context.Context, marketID int64) ([]GetPositionsForResolutionRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserBySub(ctx context.Context, scidSub string) (GetUserBySubRow, error)
	GetUserPosition(ctx context.Context, arg GetUserPositionParams) (Position, error)
	GetUserPositions(ctx context.Context, userID int64) ([]GetUserPositionsRow, error)
	GetUserTrades(ctx context.Context, arg GetUserTradesParams) ([]GetUserTradesRow, error)
	ListAllPatches(ctx context.Context) ([]DetectedPatch, error)
	ListDeadlinePassedMarkets(ctx context.Context) ([]ListDeadlinePassedMarketsRow, error)
	ListMarkets(ctx context.Context, arg ListMarketsParams) ([]ListMarketsRow, error)
	ListNewPatches(ctx context.Context) ([]DetectedPatch, error)
	ListPendingMarkets(ctx context.Context) ([]ListPendingMarketsRow, error)
	LogAdminAdjustment(ctx context.Context, arg LogAdminAdjustmentParams) error
	MarkPatchNotified(ctx context.Context, id int64) error
	SearchUsers(ctx context.Context, pattern string) ([]SearchUsersRow, error)
	UpdateMarketStatus(ctx context.Context, arg UpdateMarketStatusParams) error
	UpdateOutcomeShares(ctx context.Context, arg UpdateOutcomeSharesParams) error
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
	UpsertPosition(ctx context.Context, arg UpsertPositionParams) error
}

var _ Querier = (*Queries)(nil)
