// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountMarkets(ctx context.Context, arg CountMarketsParams) (int64, error)
	CreateMarket(ctx context.Context, arg CreateMarketParams) (Market, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Returns titles of all non-archived markets for duplicate-title detection.
	GetActivePendingMarketTitles(ctx context.Context) ([]string, error)
	GetEnabledAutofilterRules(ctx context.Context) ([]GetEnabledAutofilterRulesRow, error)
	GetLeaderboard(ctx context.Context, limit int64) ([]GetLeaderboardRow, error)
	GetMarketByID(ctx context.Context, id int64) (GetMarketByIDRow, error)
	GetMarketPriceHistory(ctx context.Context, marketID int64) ([]GetMarketPriceHistoryRow, error)
	// Returns aggregate trade statistics for a single market.
	GetMarketStats(ctx context.Context, marketID int64) (GetMarketStatsRow, error)
	GetMarketTrades(ctx context.Context, arg GetMarketTradesParams) ([]GetMarketTradesRow, error)
	GetPositionsForResolution(ctx context.Context, marketID int64) ([]GetPositionsForResolutionRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserBySub(ctx context.Context, scidSub string) (User, error)
	GetUserPosition(ctx context.Context, arg GetUserPositionParams) (Position, error)
	GetUserPositions(ctx context.Context, userID int64) ([]GetUserPositionsRow, error)
	GetUserTrades(ctx context.Context, arg GetUserTradesParams) ([]GetUserTradesRow, error)
	ListMarkets(ctx context.Context, arg ListMarketsParams) ([]ListMarketsRow, error)
	ListPendingMarkets(ctx context.Context) ([]ListPendingMarketsRow, error)
	ResolveMarket(ctx context.Context, arg ResolveMarketParams) error
	UpdateMarketAMMState(ctx context.Context, arg UpdateMarketAMMStateParams) error
	UpdateMarketStatus(ctx context.Context, arg UpdateMarketStatusParams) error
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpsertPosition(ctx context.Context, arg UpsertPositionParams) error
}

var _ Querier = (*Queries)(nil)
