// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package db

import (
	"context"
	"time"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (user_id, market_id, outcome_id, action, shares, cost, price_at_trade)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, market_id, outcome_id, "action", shares, cost, price_at_trade, created_at
`

type CreateTradeParams struct {
	UserID       int64   `json:"user_id"`
	MarketID     int64   `json:"market_id"`
	OutcomeID    int64   `json:"outcome_id"`
	Action       string  `json:"action"`
	Shares       float64 `json:"shares"`
	Cost         int64   `json:"cost"`
	PriceAtTrade float64 `json:"price_at_trade"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, createTrade,
		arg.UserID,
		arg.MarketID,
		arg.OutcomeID,
		arg.Action,
		arg.Shares,
		arg.Cost,
		arg.PriceAtTrade,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MarketID,
		&i.OutcomeID,
		&i.Action,
		&i.Shares,
		&i.Cost,
		&i.PriceAtTrade,
		&i.CreatedAt,
	)
	return i, err
}

const getMarketStats = `-- name: GetMarketStats :one
SELECT
    COALESCE(SUM(cost), 0)          AS total_volume,
    COUNT(DISTINCT user_id)         AS trader_count,
    COUNT(*)                        AS trade_count
FROM trades
WHERE market_id = ?
`

type GetMarketStatsRow struct {
	TotalVolume interface{} `json:"total_volume"`
	TraderCount int64       `json:"trader_count"`
	TradeCount  int64       `json:"trade_count"`
}

// Returns aggregate trade statistics for a single market.
func (q *Queries) GetMarketStats(ctx context.Context, marketID int64) (GetMarketStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getMarketStats, marketID)
	var i GetMarketStatsRow
	err := row.Scan(&i.TotalVolume, &i.TraderCount, &i.TradeCount)
	return i, err
}

const getMarketTrades = `-- name: GetMarketTrades :many
SELECT t.id, t.user_id, t.market_id, t.outcome_id, t."action", t.shares, t.cost, t.price_at_trade, t.created_at, u.display_name AS trader_name, o.label AS outcome_label
FROM trades t
JOIN users u ON u.id = t.user_id
JOIN market_outcomes o ON o.id = t.outcome_id
WHERE t.market_id = ?
ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type GetMarketTradesParams struct {
	MarketID int64 `json:"market_id"`
	Limit    int64 `json:"limit"`
	Offset   int64 `json:"offset"`
}

type GetMarketTradesRow struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	MarketID     int64     `json:"market_id"`
	OutcomeID    int64     `json:"outcome_id"`
	Action       string    `json:"action"`
	Shares       float64   `json:"shares"`
	Cost         int64     `json:"cost"`
	PriceAtTrade float64   `json:"price_at_trade"`
	CreatedAt    time.Time `json:"created_at"`
	TraderName   string    `json:"trader_name"`
	OutcomeLabel string    `json:"outcome_label"`
}

func (q *Queries) GetMarketTrades(ctx context.Context, arg GetMarketTradesParams) ([]GetMarketTradesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMarketTrades, arg.MarketID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMarketTradesRow{}
	for rows.Next() {
		var i GetMarketTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Action,
			&i.Shares,
			&i.Cost,
			&i.PriceAtTrade,
			&i.CreatedAt,
			&i.TraderName,
			&i.OutcomeLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositionsForResolution = `-- name: GetPositionsForResolution :many
SELECT p.user_id, p.outcome_id, p.shares
FROM positions p
WHERE p.market_id = ?
  AND p.shares > 0
`

type GetPositionsForResolutionRow struct {
	UserID    int64   `json:"user_id"`
	OutcomeID int64   `json:"outcome_id"`
	Shares    float64 `json:"shares"`
}

func (q *Queries) GetPositionsForResolution(ctx context.Context, marketID int64) ([]GetPositionsForResolutionRow, error) {
	rows, err := q.db.QueryContext(ctx, getPositionsForResolution, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPositionsForResolutionRow{}
	for rows.Next() {
		var i GetPositionsForResolutionRow
		if err := rows.Scan(&i.UserID, &i.OutcomeID, &i.Shares); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPosition = `-- name: GetUserPosition :one
SELECT user_id, market_id, outcome_id, shares
FROM positions
WHERE user_id = ? AND market_id = ? AND outcome_id = ?
LIMIT 1
`

type GetUserPositionParams struct {
	UserID    int64 `json:"user_id"`
	MarketID  int64 `json:"market_id"`
	OutcomeID int64 `json:"outcome_id"`
}

func (q *Queries) GetUserPosition(ctx context.Context, arg GetUserPositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, getUserPosition, arg.UserID, arg.MarketID, arg.OutcomeID)
	var i Position
	err := row.Scan(
		&i.UserID,
		&i.MarketID,
		&i.OutcomeID,
		&i.Shares,
	)
	return i, err
}

const getUserPositions = `-- name: GetUserPositions :many
SELECT p.user_id, p.market_id, p.outcome_id, p.shares, m.title AS market_title, m.status AS market_status,
       m.liquidity_param, o.label AS outcome_label
FROM positions p
JOIN markets m ON m.id = p.market_id
JOIN market_outcomes o ON o.id = p.outcome_id
WHERE p.user_id = ?
  AND p.shares > 0
`

type GetUserPositionsRow struct {
	UserID         int64   `json:"user_id"`
	MarketID       int64   `json:"market_id"`
	OutcomeID      int64   `json:"outcome_id"`
	Shares         float64 `json:"shares"`
	MarketTitle    string  `json:"market_title"`
	MarketStatus   string  `json:"market_status"`
	LiquidityParam float64 `json:"liquidity_param"`
	OutcomeLabel   string  `json:"outcome_label"`
}

func (q *Queries) GetUserPositions(ctx context.Context, userID int64) ([]GetUserPositionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPositions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPositionsRow{}
	for rows.Next() {
		var i GetUserPositionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Shares,
			&i.MarketTitle,
			&i.MarketStatus,
			&i.LiquidityParam,
			&i.OutcomeLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTrades = `-- name: GetUserTrades :many
SELECT t.id, t.user_id, t.market_id, t.outcome_id, t."action", t.shares, t.cost, t.price_at_trade, t.created_at, m.title AS market_title, o.label AS outcome_label
FROM trades t
JOIN markets m ON m.id = t.market_id
JOIN market_outcomes o ON o.id = t.outcome_id
WHERE t.user_id = ?
ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type GetUserTradesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetUserTradesRow struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	MarketID     int64     `json:"market_id"`
	OutcomeID    int64     `json:"outcome_id"`
	Action       string    `json:"action"`
	Shares       float64   `json:"shares"`
	Cost         int64     `json:"cost"`
	PriceAtTrade float64   `json:"price_at_trade"`
	CreatedAt    time.Time `json:"created_at"`
	MarketTitle  string    `json:"market_title"`
	OutcomeLabel string    `json:"outcome_label"`
}

func (q *Queries) GetUserTrades(ctx context.Context, arg GetUserTradesParams) ([]GetUserTradesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTrades, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTradesRow{}
	for rows.Next() {
		var i GetUserTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.OutcomeID,
			&i.Action,
			&i.Shares,
			&i.Cost,
			&i.PriceAtTrade,
			&i.CreatedAt,
			&i.MarketTitle,
			&i.OutcomeLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (user_id, market_id, outcome_id, shares)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, market_id, outcome_id) DO UPDATE SET
    shares = positions.shares + excluded.shares
`

type UpsertPositionParams struct {
	UserID    int64   `json:"user_id"`
	MarketID  int64   `json:"market_id"`
	OutcomeID int64   `json:"outcome_id"`
	Shares    float64 `json:"shares"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPosition,
		arg.UserID,
		arg.MarketID,
		arg.OutcomeID,
		arg.Shares,
	)
	return err
}
