// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package db

import (
	"context"
	"time"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (user_id, market_id, side, action, shares, cost, price_at_trade)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, market_id, side, "action", shares, cost, price_at_trade, created_at
`

type CreateTradeParams struct {
	UserID       int64   `json:"user_id"`
	MarketID     int64   `json:"market_id"`
	Side         string  `json:"side"`
	Action       string  `json:"action"`
	Shares       float64 `json:"shares"`
	Cost         int64   `json:"cost"`
	PriceAtTrade float64 `json:"price_at_trade"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, createTrade,
		arg.UserID,
		arg.MarketID,
		arg.Side,
		arg.Action,
		arg.Shares,
		arg.Cost,
		arg.PriceAtTrade,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MarketID,
		&i.Side,
		&i.Action,
		&i.Shares,
		&i.Cost,
		&i.PriceAtTrade,
		&i.CreatedAt,
	)
	return i, err
}

const getMarketTrades = `-- name: GetMarketTrades :many
SELECT t.id, t.user_id, t.market_id, t.side, t."action", t.shares, t.cost, t.price_at_trade, t.created_at, u.display_name AS trader_name
FROM trades t
JOIN users u ON u.id = t.user_id
WHERE t.market_id = ?
ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type GetMarketTradesParams struct {
	MarketID int64 `json:"market_id"`
	Limit    int64 `json:"limit"`
	Offset   int64 `json:"offset"`
}

type GetMarketTradesRow struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	MarketID     int64     `json:"market_id"`
	Side         string    `json:"side"`
	Action       string    `json:"action"`
	Shares       float64   `json:"shares"`
	Cost         int64     `json:"cost"`
	PriceAtTrade float64   `json:"price_at_trade"`
	CreatedAt    time.Time `json:"created_at"`
	TraderName   string    `json:"trader_name"`
}

func (q *Queries) GetMarketTrades(ctx context.Context, arg GetMarketTradesParams) ([]GetMarketTradesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMarketTrades, arg.MarketID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMarketTradesRow{}
	for rows.Next() {
		var i GetMarketTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.Side,
			&i.Action,
			&i.Shares,
			&i.Cost,
			&i.PriceAtTrade,
			&i.CreatedAt,
			&i.TraderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositionsForResolution = `-- name: GetPositionsForResolution :many
SELECT user_id, yes_shares, no_shares
FROM positions
WHERE market_id = ?
  AND (yes_shares > 0 OR no_shares > 0)
`

type GetPositionsForResolutionRow struct {
	UserID    int64   `json:"user_id"`
	YesShares float64 `json:"yes_shares"`
	NoShares  float64 `json:"no_shares"`
}

func (q *Queries) GetPositionsForResolution(ctx context.Context, marketID int64) ([]GetPositionsForResolutionRow, error) {
	rows, err := q.db.QueryContext(ctx, getPositionsForResolution, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPositionsForResolutionRow{}
	for rows.Next() {
		var i GetPositionsForResolutionRow
		if err := rows.Scan(&i.UserID, &i.YesShares, &i.NoShares); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPosition = `-- name: GetUserPosition :one
SELECT user_id, market_id, yes_shares, no_shares
FROM positions
WHERE user_id = ? AND market_id = ?
LIMIT 1
`

type GetUserPositionParams struct {
	UserID   int64 `json:"user_id"`
	MarketID int64 `json:"market_id"`
}

func (q *Queries) GetUserPosition(ctx context.Context, arg GetUserPositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, getUserPosition, arg.UserID, arg.MarketID)
	var i Position
	err := row.Scan(
		&i.UserID,
		&i.MarketID,
		&i.YesShares,
		&i.NoShares,
	)
	return i, err
}

const getUserPositions = `-- name: GetUserPositions :many
SELECT p.user_id, p.market_id, p.yes_shares, p.no_shares, m.title AS market_title, m.status AS market_status,
       m.yes_shares AS pool_yes, m.no_shares AS pool_no, m.liquidity_param
FROM positions p
JOIN markets m ON m.id = p.market_id
WHERE p.user_id = ?
  AND (p.yes_shares > 0 OR p.no_shares > 0)
`

type GetUserPositionsRow struct {
	UserID         int64   `json:"user_id"`
	MarketID       int64   `json:"market_id"`
	YesShares      float64 `json:"yes_shares"`
	NoShares       float64 `json:"no_shares"`
	MarketTitle    string  `json:"market_title"`
	MarketStatus   string  `json:"market_status"`
	PoolYes        float64 `json:"pool_yes"`
	PoolNo         float64 `json:"pool_no"`
	LiquidityParam float64 `json:"liquidity_param"`
}

func (q *Queries) GetUserPositions(ctx context.Context, userID int64) ([]GetUserPositionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPositions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPositionsRow{}
	for rows.Next() {
		var i GetUserPositionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.MarketID,
			&i.YesShares,
			&i.NoShares,
			&i.MarketTitle,
			&i.MarketStatus,
			&i.PoolYes,
			&i.PoolNo,
			&i.LiquidityParam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTrades = `-- name: GetUserTrades :many
SELECT t.id, t.user_id, t.market_id, t.side, t."action", t.shares, t.cost, t.price_at_trade, t.created_at, m.title AS market_title
FROM trades t
JOIN markets m ON m.id = t.market_id
WHERE t.user_id = ?
ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type GetUserTradesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetUserTradesRow struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	MarketID     int64     `json:"market_id"`
	Side         string    `json:"side"`
	Action       string    `json:"action"`
	Shares       float64   `json:"shares"`
	Cost         int64     `json:"cost"`
	PriceAtTrade float64   `json:"price_at_trade"`
	CreatedAt    time.Time `json:"created_at"`
	MarketTitle  string    `json:"market_title"`
}

func (q *Queries) GetUserTrades(ctx context.Context, arg GetUserTradesParams) ([]GetUserTradesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTrades, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTradesRow{}
	for rows.Next() {
		var i GetUserTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MarketID,
			&i.Side,
			&i.Action,
			&i.Shares,
			&i.Cost,
			&i.PriceAtTrade,
			&i.CreatedAt,
			&i.MarketTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (user_id, market_id, yes_shares, no_shares)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, market_id) DO UPDATE SET
    yes_shares = positions.yes_shares + excluded.yes_shares,
    no_shares  = positions.no_shares  + excluded.no_shares
`

type UpsertPositionParams struct {
	UserID    int64   `json:"user_id"`
	MarketID  int64   `json:"market_id"`
	YesShares float64 `json:"yes_shares"`
	NoShares  float64 `json:"no_shares"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPosition,
		arg.UserID,
		arg.MarketID,
		arg.YesShares,
		arg.NoShares,
	)
	return err
}
