// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (scid_sub, display_name, email)
VALUES (?, ?, ?)
RETURNING id, scid_sub, display_name, email, balance, is_moderator, is_admin, created_at, last_login_at,
          rsi_handle, rsi_verified_at, rsi_enlisted, rsi_citizen_record, avatar_url, is_rsi_verified
`

type CreateUserParams struct {
	ScidSub     string `json:"scid_sub"`
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ScidSub, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ScidSub,
		&i.DisplayName,
		&i.Email,
		&i.Balance,
		&i.IsModerator,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.RsiHandle,
		&i.RsiVerifiedAt,
		&i.RsiEnlisted,
		&i.RsiCitizenRecord,
		&i.AvatarUrl,
		&i.IsRsiVerified,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT u.id, u.display_name, u.balance,
       COALESCE(SUM(
           CASE
               WHEN p.yes_shares > 0 AND m.status = 'active' THEN
                   CAST(p.yes_shares * (1.0 / (1.0 + exp((m.no_shares - m.yes_shares) / m.liquidity_param)) * 100) AS INTEGER)
               WHEN p.no_shares > 0 AND m.status = 'active' THEN
                   CAST(p.no_shares * (1.0 / (1.0 + exp((m.yes_shares - m.no_shares) / m.liquidity_param)) * 100) AS INTEGER)
               ELSE 0
           END
       ), 0) AS portfolio_value
FROM users u
LEFT JOIN positions p ON p.user_id = u.id
LEFT JOIN markets m ON m.id = p.market_id
GROUP BY u.id
ORDER BY (u.balance + portfolio_value) DESC
LIMIT ?
`

type GetLeaderboardRow struct {
	ID             int64       `json:"id"`
	DisplayName    string      `json:"display_name"`
	Balance        int64       `json:"balance"`
	PortfolioValue interface{} `json:"portfolio_value"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, limit int64) ([]GetLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardRow{}
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Balance,
			&i.PortfolioValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, scid_sub, display_name, email, balance, is_moderator, is_admin, created_at, last_login_at,
       rsi_handle, rsi_verified_at, rsi_enlisted, rsi_citizen_record, avatar_url, is_rsi_verified
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ScidSub,
		&i.DisplayName,
		&i.Email,
		&i.Balance,
		&i.IsModerator,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.RsiHandle,
		&i.RsiVerifiedAt,
		&i.RsiEnlisted,
		&i.RsiCitizenRecord,
		&i.AvatarUrl,
		&i.IsRsiVerified,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, scid_sub, display_name, email, balance, is_moderator, is_admin, created_at, last_login_at,
       rsi_handle, rsi_verified_at, rsi_enlisted, rsi_citizen_record, avatar_url, is_rsi_verified
FROM users
WHERE scid_sub = ?
LIMIT 1
`

func (q *Queries) GetUserBySub(ctx context.Context, scidSub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySub, scidSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ScidSub,
		&i.DisplayName,
		&i.Email,
		&i.Balance,
		&i.IsModerator,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.RsiHandle,
		&i.RsiVerifiedAt,
		&i.RsiEnlisted,
		&i.RsiCitizenRecord,
		&i.AvatarUrl,
		&i.IsRsiVerified,
	)
	return i, err
}

const updateUserBalance = `-- name: UpdateUserBalance :exec
UPDATE users
SET balance = balance + ?
WHERE id = ?
`

type UpdateUserBalanceParams struct {
	Balance int64 `json:"balance"`
	ID      int64 `json:"id"`
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBalance, arg.Balance, arg.ID)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at      = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    display_name       = ?,
    email              = ?,
    rsi_handle         = ?,
    rsi_verified_at    = ?,
    rsi_enlisted       = ?,
    rsi_citizen_record = ?,
    avatar_url         = ?,
    is_rsi_verified    = ?
WHERE id = ?
`

type UpdateUserLastLoginParams struct {
	DisplayName      string  `json:"display_name"`
	Email            string  `json:"email"`
	RsiHandle        *string `json:"rsi_handle"`
	RsiVerifiedAt    *string `json:"rsi_verified_at"`
	RsiEnlisted      *string `json:"rsi_enlisted"`
	RsiCitizenRecord *string `json:"rsi_citizen_record"`
	AvatarUrl        *string `json:"avatar_url"`
	IsRsiVerified    int64   `json:"is_rsi_verified"`
	ID               int64   `json:"id"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin,
		arg.DisplayName,
		arg.Email,
		arg.RsiHandle,
		arg.RsiVerifiedAt,
		arg.RsiEnlisted,
		arg.RsiCitizenRecord,
		arg.AvatarUrl,
		arg.IsRsiVerified,
		arg.ID,
	)
	return err
}
