// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (scid_sub, display_name, email)
VALUES (?, ?, ?)
RETURNING id, scid_sub, display_name, email, balance, is_moderator, is_admin, created_at, last_login_at,
          rsi_handle, rsi_verified_at, rsi_enlisted, rsi_citizen_record, avatar_url, is_rsi_verified
`

type CreateUserParams struct {
	ScidSub     string `json:"scid_sub"`
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
}

type CreateUserRow struct {
	ID               int64     `json:"id"`
	ScidSub          string    `json:"scid_sub"`
	DisplayName      string    `json:"display_name"`
	Email            string    `json:"email"`
	Balance          int64     `json:"balance"`
	IsModerator      int64     `json:"is_moderator"`
	IsAdmin          int64     `json:"is_admin"`
	CreatedAt        time.Time `json:"created_at"`
	LastLoginAt      time.Time `json:"last_login_at"`
	RsiHandle        *string   `json:"rsi_handle"`
	RsiVerifiedAt    *string   `json:"rsi_verified_at"`
	RsiEnlisted      *string   `json:"rsi_enlisted"`
	RsiCitizenRecord *string   `json:"rsi_citizen_record"`
	AvatarUrl        *string   `json:"avatar_url"`
	IsRsiVerified    int64     `json:"is_rsi_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ScidSub, arg.DisplayName, arg.Email)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.ScidSub,
		&i.DisplayName,
		&i.Email,
		&i.Balance,
		&i.IsModerator,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.RsiHandle,
		&i.RsiVerifiedAt,
		&i.RsiEnlisted,
		&i.RsiCitizenRecord,
		&i.AvatarUrl,
		&i.IsRsiVerified,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT u.id, u.display_name, u.balance,
       COALESCE(SUM(
           CASE
               WHEN p.shares > 0 AND m.status = 'active' THEN
                   CAST(p.shares *
                       exp(o.shares / m.liquidity_param) /
                       (SELECT SUM(exp(o2.shares / m.liquidity_param))
                        FROM market_outcomes o2
                        WHERE o2.market_id = m.id)
                   * 100 AS INTEGER)
               ELSE 0
           END
       ), 0) AS portfolio_value
FROM users u
LEFT JOIN positions p ON p.user_id = u.id
LEFT JOIN markets m ON m.id = p.market_id
LEFT JOIN market_outcomes o ON o.id = p.outcome_id
GROUP BY u.id
ORDER BY (u.balance + portfolio_value) DESC
LIMIT ?
`

type GetLeaderboardRow struct {
	ID             int64       `json:"id"`
	DisplayName    string      `json:"display_name"`
	Balance        int64       `json:"balance"`
	PortfolioValue interface{} `json:"portfolio_value"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, limit int64) ([]GetLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardRow{}
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Balance,
			&i.PortfolioValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, scid_sub, display_name, email, balance, is_moderator, is_admin, created_at, last_login_at,
       rsi_handle, rsi_verified_at, rsi_enlisted, rsi_citizen_record, avatar_url, is_rsi_verified
FROM users
WHERE id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	ID               int64     `json:"id"`
	ScidSub          string    `json:"scid_sub"`
	DisplayName      string    `json:"display_name"`
	Email            string    `json:"email"`
	Balance          int64     `json:"balance"`
	IsModerator      int64     `json:"is_moderator"`
	IsAdmin          int64     `json:"is_admin"`
	CreatedAt        time.Time `json:"created_at"`
	LastLoginAt      time.Time `json:"last_login_at"`
	RsiHandle        *string   `json:"rsi_handle"`
	RsiVerifiedAt    *string   `json:"rsi_verified_at"`
	RsiEnlisted      *string   `json:"rsi_enlisted"`
	RsiCitizenRecord *string   `json:"rsi_citizen_record"`
	AvatarUrl        *string   `json:"avatar_url"`
	IsRsiVerified    int64     `json:"is_rsi_verified"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.ScidSub,
		&i.DisplayName,
		&i.Email,
		&i.Balance,
		&i.IsModerator,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.RsiHandle,
		&i.RsiVerifiedAt,
		&i.RsiEnlisted,
		&i.RsiCitizenRecord,
		&i.AvatarUrl,
		&i.IsRsiVerified,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, scid_sub, display_name, email, balance, is_moderator, is_admin, created_at, last_login_at,
       rsi_handle, rsi_verified_at, rsi_enlisted, rsi_citizen_record, avatar_url, is_rsi_verified
FROM users
WHERE scid_sub = ?
LIMIT 1
`

type GetUserBySubRow struct {
	ID               int64     `json:"id"`
	ScidSub          string    `json:"scid_sub"`
	DisplayName      string    `json:"display_name"`
	Email            string    `json:"email"`
	Balance          int64     `json:"balance"`
	IsModerator      int64     `json:"is_moderator"`
	IsAdmin          int64     `json:"is_admin"`
	CreatedAt        time.Time `json:"created_at"`
	LastLoginAt      time.Time `json:"last_login_at"`
	RsiHandle        *string   `json:"rsi_handle"`
	RsiVerifiedAt    *string   `json:"rsi_verified_at"`
	RsiEnlisted      *string   `json:"rsi_enlisted"`
	RsiCitizenRecord *string   `json:"rsi_citizen_record"`
	AvatarUrl        *string   `json:"avatar_url"`
	IsRsiVerified    int64     `json:"is_rsi_verified"`
}

func (q *Queries) GetUserBySub(ctx context.Context, scidSub string) (GetUserBySubRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBySub, scidSub)
	var i GetUserBySubRow
	err := row.Scan(
		&i.ID,
		&i.ScidSub,
		&i.DisplayName,
		&i.Email,
		&i.Balance,
		&i.IsModerator,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.RsiHandle,
		&i.RsiVerifiedAt,
		&i.RsiEnlisted,
		&i.RsiCitizenRecord,
		&i.AvatarUrl,
		&i.IsRsiVerified,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, display_name, rsi_handle, balance
FROM users
WHERE display_name LIKE ?1
   OR (rsi_handle IS NOT NULL AND rsi_handle LIKE ?1)
ORDER BY display_name
LIMIT 10
`

type SearchUsersRow struct {
	ID          int64   `json:"id"`
	DisplayName string  `json:"display_name"`
	RsiHandle   *string `json:"rsi_handle"`
	Balance     int64   `json:"balance"`
}

func (q *Queries) SearchUsers(ctx context.Context, pattern string) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.RsiHandle,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserBalance = `-- name: UpdateUserBalance :exec
UPDATE users
SET balance = balance + ?
WHERE id = ?
`

type UpdateUserBalanceParams struct {
	Balance int64 `json:"balance"`
	ID      int64 `json:"id"`
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBalance, arg.Balance, arg.ID)
	return err
}
